### ISSUE TITLE
Error when executing the binary  [TypeError: NTLMRelayxConfig.setLDAPOptions() missing 1 required positional argument: 'adddnsrecord']

### ISSUE THREAD

**Issue by MaxBDO** [LuemmelSec/ntlmrelayx.py_to_exe#2]
So, I'm getting the following error when running the binary:

PS C:\Python\dist> .\ntlmrelayx.exe -t http://adcs.local/certsrv/certfnsh.asp -smb2support --adcs
Impacket v0.11.0 - Copyright 2023 Fortra

[*] Protocol Client DCSYNC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAP loaded..
[*] Running in relay mode to single host
Traceback (most recent call last):
   File "ntlmrelayx.py", line 475, in <module>
   File "ntlmrelayx.py", line 178, in start_servers
TypeError: NTLMRelayxConfig.setLDAPOptions() missing 1 required positional argument: 'adddnsrecord'
[35208] Failed to execute script 'ntlmrelayx' due to unhandled exception!

I installed it as shown in the README.

Looking for the error "TypeError: NTLMRelayxConfig.setLDAPOptions() missing 1 required positional argument: 'adddnsrecord'" I found this link: https://github.com/fortra/impacket/issues/1459

Apparently it's a problem related to the impacket version - I'm using the latest version impacket in c:\python\lib\site-packages (0.11.0) - Or it's related to the python version, but I'm using one of the most recent versions .

PS C:\Python\dist> python --version
Python 3.12.2

I did the conversion based on your already modified file (https://github.com/LuemmelSec/ntlmrelayx.py_to_exe/blob/main/ntlmrelayx.py)

Have you ever seen this error message?

**Comment by LuemmelSec** [comment]
This looks like a problem with the ntlmrelayx.py  you provide it and the INSTALLED version of impacket. Either get the ntlmrelayx.py from the installed pip packages, or completely get rid of impacket and install it freshly.

**Comment by Moneysac90** [comment]
We had exactly the same issue today. We patched the `ntlmrelayx.py` from our current impaket installation according to the description in the repository and it was working fine.

**Comment by MaxBDO** [comment]
Thanks guys, it worked after modifying the latest version of `ntlmrelayx.py`.
